project_id = "bvjulkcmzfzyfwobwlnx"

[functions.ai-assistant]
verify_jwt = false

[functions.efi-register-webhooks]
verify_jwt = true

[functions.moderate-content]
verify_jwt = true

[functions.create-stripe-connected-account]
verify_jwt = true

[functions.create-project-payment]
verify_jwt = true

[functions.create-negotiation-payment]
verify_jwt = true

[functions.release-payment]
verify_jwt = true

[functions.stripe-webhook-handler]
verify_jwt = false

[functions.buy-woorkoins]
verify_jwt = true

[functions.efi-create-pix-charge]
verify_jwt = true

[functions.efi-create-card-charge]
verify_jwt = true

[functions.efi-webhook]
verify_jwt = false

[functions.verify-identity-document]
verify_jwt = true

[functions.moderate-message]
verify_jwt = true
